// Tradução da interface do bpmn-js (paleta, menu de contexto, popup "trocar tipo") para
// português do Brasil. A lista de chaves foi extraída diretamente do código-fonte instalado em
// node_modules/bpmn-js e node_modules/diagram-js (todas as chamadas translate('...') e os labels
// do menu "trocar tipo" em PopupEntries.js) — se uma versão futura do bpmn-js adicionar textos
// novos, eles simplesmente aparecem em inglês (fallback do customTranslate abaixo) até serem
// adicionados aqui.
const DICIONARIO_PT_BR = {
  'Activate create/remove space tool': 'Espaço — clique e arraste para abrir ou fechar espaço entre elementos',
  'Activate global connect tool': 'Conectar — ligue dois elementos quaisquer clicando um e depois o outro',
  'Activate hand tool': 'Mão — clique e arraste para mover a área visível do diagrama',
  'Activate lasso tool': 'Laço — selecione vários elementos desenhando uma área ao redor deles',
  'Ad-hoc sub-process': 'Subprocesso ad-hoc',
  'Ad-hoc sub-process (collapsed)': 'Subprocesso ad-hoc (recolhido)',
  'Ad-hoc sub-process (expanded)': 'Subprocesso ad-hoc (expandido)',
  'Add lane above': 'Adiciona uma nova raia acima da atual',
  'Add lane below': 'Adiciona uma nova raia abaixo da atual',
  'Add text annotation': 'Anotação — adiciona uma nota de texto explicativa ao diagrama',
  'Align elements': 'Alinha os elementos selecionados',
  'Append compensation activity': 'Adiciona uma atividade de compensação depois deste elemento',
  'Append conditional intermediate catch event': 'Adiciona um evento intermediário condicional depois deste elemento',
  'Append end event': 'Adiciona um evento de fim depois deste elemento',
  'Append gateway': 'Adiciona um gateway (ponto de decisão) depois deste elemento',
  'Append intermediate/boundary event': 'Adiciona um evento intermediário depois deste elemento',
  'Append message intermediate catch event': 'Adiciona um evento intermediário de mensagem depois deste elemento',
  'Append receive task': 'Adiciona uma tarefa de recebimento depois deste elemento',
  'Append signal intermediate catch event': 'Adiciona um evento intermediário de sinal depois deste elemento',
  'Append task': 'Adiciona uma tarefa depois deste elemento',
  'Append timer intermediate catch event': 'Adiciona um evento intermediário de temporizador depois deste elemento',
  'Boundary event': 'Evento de limite',
  'Business rule task': 'Tarefa de regra de negócio',
  'Call activity': 'Atividade de chamada',
  'Cancel boundary event': 'Evento de limite de cancelamento',
  'Cancel end event': 'Evento de fim de cancelamento',
  'Change element': 'Troca o tipo deste elemento',
  'Collection': 'Marca este elemento como uma coleção',
  'Compensation boundary event': 'Evento de limite de compensação',
  'Compensation end event': 'Evento de fim de compensação',
  'Compensation intermediate throw event': 'Evento intermediário de lançamento de compensação',
  'Compensation start event': 'Evento de início de compensação',
  'Complex gateway': 'Gateway complexo',
  'Conditional boundary event': 'Evento de limite condicional',
  'Conditional boundary event (non-interrupting)': 'Evento de limite condicional (não interruptivo)',
  'Conditional flow': 'Fluxo condicional',
  'Conditional intermediate catch event': 'Evento intermediário de captura condicional',
  'Conditional start event': 'Evento de início condicional',
  'Conditional start event (non-interrupting)': 'Evento de início condicional (não interruptivo)',
  'Connect to other element': 'Conecta este elemento a outro através de um fluxo',
  'Connect using association': 'Conecta usando uma associação (referência, sem indicar sequência)',
  'Connect using data input association': 'Conecta a um objeto ou repositório de dados',
  'Create data object reference': 'Objeto de dados — representa uma informação usada ou gerada no processo',
  'Create data store reference': 'Repositório de dados — representa uma base de dados usada no processo',
  'Create end event': 'Evento de fim — marca o término do processo',
  'Create expanded sub-process': 'Subprocesso — agrupa uma sequência de etapas em um único bloco',
  'Create gateway': 'Gateway — ponto de decisão ou divisão do fluxo',
  'Create group': 'Grupo — agrupa elementos visualmente, sem efeito na execução',
  'Create intermediate/boundary event': 'Evento intermediário/limite — ocorre durante o processo ou é anexado a uma atividade',
  'Create pool/participant': 'Pool/participante — representa uma área, papel ou empresa do processo',
  'Create start event': 'Evento de início — marca o começo do processo',
  'Create task': 'Tarefa — atividade realizada por uma pessoa ou sistema',
  'Data object reference': 'Referência de objeto de dados',
  'Data store reference': 'Referência de repositório de dados',
  'Default flow': 'Fluxo padrão',
  'Delete': 'Excluir o elemento selecionado',
  'Distribute elements horizontally': 'Distribui os elementos selecionados uniformemente na horizontal',
  'Distribute elements vertically': 'Distribui os elementos selecionados uniformemente na vertical',
  'Divide into three lanes': 'Divide este pool em três raias',
  'Divide into two lanes': 'Divide este pool em duas raias',
  'Empty pool/participant': 'Pool vazio/participante',
  'End event': 'Evento de fim',
  'Error boundary event': 'Evento de limite de erro',
  'Error end event': 'Evento de fim de erro',
  'Error start event': 'Evento de início de erro',
  'Escalation boundary event': 'Evento de limite de escalonamento',
  'Escalation boundary event (non-interrupting)': 'Evento de limite de escalonamento (não interruptivo)',
  'Escalation end event': 'Evento de fim de escalonamento',
  'Escalation intermediate throw event': 'Evento intermediário de lançamento de escalonamento',
  'Escalation start event': 'Evento de início de escalonamento',
  'Escalation start event (non-interrupting)': 'Evento de início de escalonamento (não interruptivo)',
  'Event based instantiating Gateway': 'Gateway instanciador baseado em eventos',
  'Event sub-process': 'Subprocesso de evento',
  'Event-based gateway': 'Gateway baseado em eventos',
  'Exclusive gateway': 'Gateway exclusivo',
  'Expanded pool/participant': 'Pool/participante expandido',
  'Inclusive gateway': 'Gateway inclusivo',
  'Intermediate throw event': 'Evento intermediário de lançamento',
  'Link intermediate catch event': 'Evento intermediário de captura de link',
  'Link intermediate throw event': 'Evento intermediário de lançamento de link',
  'Loop': 'Marca esta atividade como repetitiva (loop)',
  'Manual task': 'Tarefa manual',
  'Message boundary event': 'Evento de limite de mensagem',
  'Message boundary event (non-interrupting)': 'Evento de limite de mensagem (não interruptivo)',
  'Message end event': 'Evento de fim de mensagem',
  'Message intermediate catch event': 'Evento intermediário de captura de mensagem',
  'Message intermediate throw event': 'Evento intermediário de lançamento de mensagem',
  'Message start event': 'Evento de início de mensagem',
  'Message start event (non-interrupting)': 'Evento de início de mensagem (não interruptivo)',
  'Open {element}': 'Abrir {element}',
  'Parallel Event based instantiating Gateway': 'Gateway instanciador paralelo baseado em eventos',
  'Parallel gateway': 'Gateway paralelo',
  'Parallel multi-instance': 'Marca esta atividade para rodar em várias instâncias em paralelo',
  'Participant multiplicity': 'Permite múltiplos participantes neste pool',
  'Receive task': 'Tarefa de recebimento',
  'Script task': 'Tarefa de script',
  'Search in diagram': 'Pesquisar um elemento pelo nome no diagrama',
  'Send task': 'Tarefa de envio',
  'Sequence flow': 'Fluxo de sequência',
  'Sequential multi-instance': 'Marca esta atividade para rodar em várias instâncias em sequência',
  'Service task': 'Tarefa de serviço',
  'Signal boundary event': 'Evento de limite de sinal',
  'Signal boundary event (non-interrupting)': 'Evento de limite de sinal (não interruptivo)',
  'Signal end event': 'Evento de fim de sinal',
  'Signal intermediate catch event': 'Evento intermediário de captura de sinal',
  'Signal intermediate throw event': 'Evento intermediário de lançamento de sinal',
  'Signal start event': 'Evento de início de sinal',
  'Signal start event (non-interrupting)': 'Evento de início de sinal (não interruptivo)',
  'Start event': 'Evento de início',
  'Sub-process': 'Subprocesso',
  'Sub-process (collapsed)': 'Subprocesso (recolhido)',
  'Sub-process (expanded)': 'Subprocesso (expandido)',
  'Task': 'Tarefa',
  'Terminate end event': 'Evento de fim de término',
  'Timer boundary event': 'Evento de limite de temporizador',
  'Timer boundary event (non-interrupting)': 'Evento de limite de temporizador (não interruptivo)',
  'Timer intermediate catch event': 'Evento intermediário de captura de temporizador',
  'Timer start event': 'Evento de início de temporizador',
  'Timer start event (non-interrupting)': 'Evento de início de temporizador (não interruptivo)',
  'Toggle non-interrupting': 'Alterna entre evento interruptivo e não interruptivo',
  'Transaction': 'Transação',
  'User task': 'Tarefa de usuário',
}

function customTranslate(template, replacements) {
  replacements = replacements || {}
  template = DICIONARIO_PT_BR[template] || template
  return template.replace(/{([^}]+)}/g, (_, key) => replacements[key] || `{${key}}`)
}

// Módulo no formato esperado por additionalModules do bpmn-js/diagram-js (substitui o serviço
// 'translate' padrão pelo nosso).
export const bpmnTranslatePtBrModule = {
  translate: ['value', customTranslate],
}

// Descrição (dica ao passar o mouse) do que cada tipo de elemento serve, mostrada no popup
// "Alterar elemento" — chave é o rótulo já traduzido (igual ao valor em DICIONARIO_PT_BR acima).
const DESCRICOES_ELEMENTOS = {
  'Tarefa': 'Atividade genérica: um passo do processo sem um tipo específico definido.',
  'Tarefa de usuário': 'Etapa feita por uma pessoa — gera uma tarefa na caixa de entrada do responsável, com formulário.',
  'Tarefa de serviço': 'Etapa executada automaticamente pelo sistema (ex.: chamar uma integração), sem intervenção humana.',
  'Tarefa de envio': 'Envia uma mensagem para outro processo ou participante.',
  'Tarefa de recebimento': 'Aguarda o recebimento de uma mensagem para o fluxo continuar.',
  'Tarefa manual': 'Etapa feita por uma pessoa fora do sistema (ex.: conferência física), sem formulário nem integração.',
  'Tarefa de regra de negócio': 'Aplica uma regra de decisão (ex.: motor de regras) para calcular um resultado usado no processo.',
  'Tarefa de script': 'Executa um script/código automaticamente, sem interface para o usuário.',
  'Atividade de chamada': 'Chama outro processo já publicado, reaproveitando-o dentro deste.',
  'Transação': 'Subprocesso tratado como uma transação: ou tudo é concluído com sucesso, ou tudo é desfeito.',
  'Subprocesso de evento': 'Subprocesso disparado por um evento (ex.: mensagem, erro), separado do fluxo principal.',
  'Subprocesso (recolhido)': 'Agrupa uma sequência de etapas em um único bloco, escondendo os detalhes internos.',
  'Subprocesso (expandido)': 'Agrupa uma sequência de etapas em um único bloco, mostrando os detalhes internos no diagrama.',
  'Subprocesso ad-hoc (recolhido)': 'Agrupa atividades sem ordem obrigatória entre si (podem rodar em qualquer sequência) — recolhido.',
  'Subprocesso ad-hoc (expandido)': 'Agrupa atividades sem ordem obrigatória entre si (podem rodar em qualquer sequência) — expandido.',
  'Subprocesso ad-hoc': 'Agrupa atividades sem ordem obrigatória entre si — podem ser executadas em qualquer sequência.',
  'Subprocesso': 'Agrupa uma sequência de etapas do processo em um único bloco.',
  'Gateway exclusivo': 'Ponto de decisão: o fluxo segue por apenas um dos caminhos, conforme a condição de cada um.',
  'Gateway paralelo': 'Abre (ou fecha) caminhos que rodam ao mesmo tempo, todos em paralelo.',
  'Gateway inclusivo': 'Ponto de decisão: o fluxo pode seguir por um ou mais caminhos ao mesmo tempo, conforme as condições.',
  'Gateway complexo': 'Ponto de decisão com regra de sincronização personalizada, para casos que os outros gateways não cobrem.',
  'Gateway baseado em eventos': 'O caminho seguido depende de qual evento acontecer primeiro (ex.: qual mensagem chega antes).',
  'Gateway instanciador baseado em eventos': 'Como o gateway baseado em eventos, mas também pode iniciar uma nova instância do processo.',
  'Gateway instanciador paralelo baseado em eventos': 'Inicia uma nova instância do processo quando todos os eventos configurados ocorrerem.',
  'Referência de objeto de dados': 'Representa uma informação usada ou produzida durante o processo (ex.: um documento).',
  'Referência de repositório de dados': 'Representa uma base de dados ou sistema onde informações são lidas/gravadas durante o processo.',
  'Pool/participante expandido': 'Área que representa uma empresa, sistema ou departamento, mostrando as etapas internas dela.',
  'Pool vazio/participante': 'Área que representa uma empresa, sistema ou departamento externo, sem detalhar as etapas internas dele.',
  'Evento de início': 'Marca o começo do processo — toda instância nasce a partir daqui.',
  'Evento de fim': 'Marca o término deste caminho do processo.',
  'Evento de limite': 'Anexado à borda de uma atividade — reage a algo que acontece enquanto ela está em andamento.',
  'Evento intermediário de lançamento': 'Emite algo (mensagem, sinal etc.) nesse ponto do processo, sem esperar resposta.',
  'Evento de início de mensagem': 'Inicia o processo quando uma mensagem é recebida.',
  'Evento de início de temporizador': 'Inicia o processo automaticamente em um horário definido ou após um intervalo de tempo.',
  'Evento de início condicional': 'Inicia o processo quando uma condição de negócio passa a ser verdadeira.',
  'Evento de início de sinal': 'Inicia o processo quando um sinal (broadcast) é emitido em qualquer parte do sistema.',
  'Evento de início de erro': 'Inicia um subprocesso de evento quando um erro específico ocorre no processo pai.',
  'Evento de início de escalonamento': 'Inicia um subprocesso de evento quando um escalonamento é sinalizado no processo pai.',
  'Evento de início de compensação': 'Inicia um subprocesso de compensação, usado para desfazer uma atividade já concluída.',
  'Evento de início de mensagem (não interruptivo)': 'Inicia um subprocesso de evento paralelo ao receber uma mensagem, sem interromper o fluxo principal.',
  'Evento de início de temporizador (não interruptivo)': 'Inicia um subprocesso de evento paralelo em um horário definido, sem interromper o fluxo principal.',
  'Evento de início condicional (não interruptivo)': 'Inicia um subprocesso de evento paralelo quando a condição se torna verdadeira, sem interromper o fluxo principal.',
  'Evento de início de sinal (não interruptivo)': 'Inicia um subprocesso de evento paralelo ao receber um sinal, sem interromper o fluxo principal.',
  'Evento de início de escalonamento (não interruptivo)': 'Inicia um subprocesso de evento paralelo ao receber um escalonamento, sem interromper o fluxo principal.',
  'Evento intermediário de captura de mensagem': 'Pausa o fluxo até que uma mensagem específica seja recebida.',
  'Evento intermediário de lançamento de mensagem': 'Envia uma mensagem nesse ponto do processo.',
  'Evento intermediário de captura de temporizador': 'Pausa o fluxo até um horário definido ou até passar um intervalo de tempo.',
  'Evento intermediário de lançamento de escalonamento': 'Sinaliza um escalonamento nesse ponto do processo.',
  'Evento intermediário de captura condicional': 'Pausa o fluxo até que uma condição de negócio passe a ser verdadeira.',
  'Evento intermediário de captura de link': 'Continua o fluxo a partir de um evento de lançamento de link com o mesmo nome — evita cruzar linhas no diagrama.',
  'Evento intermediário de lançamento de link': 'Aponta para um evento de captura de link com o mesmo nome, continuando o fluxo em outro ponto do diagrama.',
  'Evento intermediário de lançamento de compensação': 'Aciona a compensação (desfazer) de uma atividade já concluída.',
  'Evento intermediário de captura de sinal': 'Pausa o fluxo até que um sinal (broadcast) específico seja emitido.',
  'Evento intermediário de lançamento de sinal': 'Emite um sinal (broadcast) nesse ponto do processo, para quem estiver esperando por ele.',
  'Evento de limite de mensagem': 'Interrompe a atividade e desvia o fluxo se uma mensagem específica for recebida durante sua execução.',
  'Evento de limite de temporizador': 'Interrompe a atividade e desvia o fluxo se o tempo definido se esgotar durante sua execução.',
  'Evento de limite de escalonamento': 'Interrompe a atividade e desvia o fluxo se um escalonamento for sinalizado durante sua execução.',
  'Evento de limite condicional': 'Interrompe a atividade e desvia o fluxo se uma condição de negócio passar a ser verdadeira durante sua execução.',
  'Evento de limite de erro': 'Interrompe a atividade e desvia o fluxo se um erro específico ocorrer durante sua execução.',
  'Evento de limite de cancelamento': 'Reage ao cancelamento de uma transação, permitindo tratar o desfazimento.',
  'Evento de limite de sinal': 'Interrompe a atividade e desvia o fluxo se um sinal (broadcast) específico for recebido durante sua execução.',
  'Evento de limite de compensação': 'Aciona a compensação (desfazer) desta atividade quando ela precisar ser desfeita depois de concluída.',
  'Evento de limite de mensagem (não interruptivo)': 'Dispara um caminho paralelo ao receber a mensagem, sem interromper a atividade original.',
  'Evento de limite de temporizador (não interruptivo)': 'Dispara um caminho paralelo quando o tempo se esgota, sem interromper a atividade original.',
  'Evento de limite de escalonamento (não interruptivo)': 'Dispara um caminho paralelo ao receber o escalonamento, sem interromper a atividade original.',
  'Evento de limite condicional (não interruptivo)': 'Dispara um caminho paralelo quando a condição se torna verdadeira, sem interromper a atividade original.',
  'Evento de limite de sinal (não interruptivo)': 'Dispara um caminho paralelo ao receber o sinal, sem interromper a atividade original.',
  'Evento de fim de mensagem': 'Encerra este caminho e envia uma mensagem ao terminar.',
  'Evento de fim de escalonamento': 'Encerra este caminho sinalizando um escalonamento para o processo pai.',
  'Evento de fim de erro': 'Encerra este caminho sinalizando um erro específico para o processo pai.',
  'Evento de fim de cancelamento': 'Encerra uma transação sinalizando seu cancelamento (desfaz o que já foi feito).',
  'Evento de fim de compensação': 'Encerra este caminho acionando a compensação (desfazer) de uma atividade já concluída.',
  'Evento de fim de sinal': 'Encerra este caminho emitindo um sinal (broadcast) para quem estiver esperando por ele.',
  'Evento de fim de término': 'Encerra imediatamente toda a instância do processo, mesmo com outras atividades em paralelo ainda em andamento.',
  'Fluxo de sequência': 'Liga duas etapas em ordem — o caminho comum de execução do processo.',
  'Fluxo padrão': 'Caminho seguido quando nenhuma das condições dos outros fluxos do gateway for verdadeira.',
  'Fluxo condicional': 'Só é seguido se a condição definida nele for verdadeira.',
}

// Decora o popup "Alterar elemento" com as descrições acima, no atributo title (dica ao passar
// o mouse). Precisa ser chamado uma vez por instância do modelador, depois que ela é criada —
// ver uso em BpmModelador.jsx.
export function registrarDescricoesElementos(modeler) {
  const popupMenu = modeler.get('popupMenu')
  // Prioridade menor que a padrão (1000) usada pelo provider 'bpmn-replace' do próprio bpmn-js,
  // para que nosso decorador rode depois e receba as entradas já preenchidas (ver PopupMenu.js
  // do diagram-js: quem registra com prioridade maior é processado primeiro).
  popupMenu.registerProvider('bpmn-replace', 500, {
    getPopupMenuEntries() {
      return (entries) => {
        Object.keys(entries).forEach(id => {
          const descricao = DESCRICOES_ELEMENTOS[entries[id].label]
          if (descricao) entries[id] = { ...entries[id], title: descricao }
        })
        return entries
      }
    },
  })
}
