-- Botões Incluir/Editar e Excluir das telas de cadastro passam a ter permissão própria
-- (permissoes_grupo_acoes). Para não tirar acesso de ninguém, cada grupo que já tem a tela
-- recebe as ações correspondentes; depois é só desmarcar onde quiser em Grupos de Acessos.
INSERT INTO permissoes_grupo_acoes (grupo_id, menu_path, acao)
SELECT pg.grupo_id, v.menu_path, v.acao
FROM permissoes_grupo pg
JOIN (VALUES
    ('agrup-cargos', 'editar'),
    ('agrup-cargos', 'excluir'),
    ('agrup-departamentos', 'editar'),
    ('agrup-departamentos', 'excluir'),
    ('agrup-empresas', 'editar'),
    ('agrup-empresas', 'excluir'),
    ('areas', 'editar'),
    ('areas', 'excluir'),
    ('bases-calculo', 'editar'),
    ('bases-calculo', 'excluir'),
    ('bi/medidas', 'editar'),
    ('bi/medidas', 'excluir'),
    ('box', 'editar'),
    ('box', 'excluir'),
    ('calendario', 'editar'),
    ('calendario', 'excluir'),
    ('cargos', 'editar'),
    ('cargos', 'excluir'),
    ('politica-comissao', 'editar'),
    ('politica-comissao', 'excluir'),
    ('cargos-remuneracoes', 'editar'),
    ('classificacao-compra', 'editar'),
    ('classificacao-compra', 'excluir'),
    ('departamentos', 'editar'),
    ('departamentos', 'excluir'),
    ('empresas', 'editar'),
    ('empresas', 'excluir'),
    ('feriados', 'editar'),
    ('ferias', 'editar'),
    ('fontes-calculo', 'editar'),
    ('fontes-calculo', 'excluir'),
    ('fontes-microwork', 'editar'),
    ('fontes-microwork', 'excluir'),
    ('fornecedores', 'editar'),
    ('funcionarios', 'editar'),
    ('funcionarios', 'excluir'),
    ('governanca/perfis-acesso', 'editar'),
    ('governanca/perfis-acesso', 'excluir'),
    ('metas/pos-vendas/distribuicao-consultores', 'editar'),
    ('metas/pos-vendas/distribuicao-consultores', 'excluir'),
    ('metas/gestao-aprovacao', 'editar'),
    ('metas/gestao-aprovacao', 'excluir'),
    ('metas/pos-vendas/pecas', 'editar'),
    ('metas/pos-vendas/servicos_pecas', 'editar'),
    ('metas/pos-vendas/servicos_pecas', 'excluir'),
    ('movimento-venda', 'editar'),
    ('movimento-venda', 'excluir'),
    ('natureza-operacoes', 'editar'),
    ('natureza-operacoes', 'excluir'),
    ('projetos/areas', 'editar'),
    ('projetos/departamentos', 'editar'),
    ('projetos/departamentos', 'excluir'),
    ('projetos/empresas', 'editar'),
    ('projetos/fases', 'editar'),
    ('projetos/fases', 'excluir'),
    ('projetos/responsaveis', 'editar'),
    ('projetos/responsaveis', 'excluir'),
    ('projetos/sistemas', 'editar'),
    ('projetos/sistemas', 'excluir'),
    ('projetos/status', 'editar'),
    ('projetos/templates', 'editar'),
    ('rubricas', 'editar'),
    ('rubricas', 'excluir'),
    ('segmentos', 'editar'),
    ('segmentos', 'excluir'),
    ('setores', 'editar'),
    ('setores', 'excluir'),
    ('sincronizacao-dados', 'editar'),
    ('tipos-os', 'editar'),
    ('tipos-os', 'excluir'),
    ('tipos-processo', 'editar'),
    ('tipos-processo', 'excluir'),
    ('tipos-produtos', 'editar'),
    ('tipos-produtos', 'excluir')
) AS v(menu_path, acao) ON pg.menu_path = v.menu_path
ON CONFLICT (grupo_id, menu_path, acao) DO NOTHING;
